name: dgl-dev-cpu
dependencies:
  - python=3.10
  - pip
  - graphviz
  - pandoc
  - pygraphviz
  - pip:
    - --find-links https://download.pytorch.org/whl/torch_stable.html
    - cmake>=3.18
    - cython
    - filelock
    - matplotlib
    - networkx
    - nltk
    - nose
    - numpy
    - ogb
    - pandas
    - psutil
    - pyarrow
    - pydantic>=2.0
    - pytest
    - pyyaml
    - rdflib
    - requests[security]
    - scikit-learn
    - scipy
    - torch==2.1.0+cpu
    - torchdata>=0.5.0
    - torcheval
    - torchmetrics
    - torch_geometric
    - tqdm
    - boto3 # AWS SDK for python
    - sphinx
    - sphinx-gallery
    - sphinx_rtd_theme
    - sphinx_copybutton
    - sphinxemoji
    - nbsphinx
    - nbsphinx-link
    - pillow
    - seaborn
    - jupyter_http_over_ws
    - ufmt
    - clang-format
    - pylint
    - lintrunner
    - jupyterlab
    - ipywidgets
    - expecttest
variables:
  DGL_HOME: /home/docs/checkouts/readthedocs.org/user_builds/pyy-dgl-doc/checkouts/latest
