name: build-dgl 

on: [push] 

jobs:
  build-dgl-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Pull DGL
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Pull Dependencies
        run: git submodule update --init --recursive

      - name: Create Conda Environment 
        run: bash ./script/create_dev_conda_env.sh -c -s
      - name: create environment with mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          auto-activate-base: false
          activate-environment: dgl-cpu
          environment-file: script/conda_env.yaml
      - name: check solution
        run: |
          mamba env export
          
      # - name: Create Conda Environment 
      #   run: bash ./script/create_dev_conda_env.sh -c -s
      # - name: init conda env
      #   run: conda init bash
      # - name: source bashrc
      #   run: source ~/.bashrc
      # - name: Switch Conda Env
      #   run: conda activate dgl-dev-cpu
      - name: Build DGL
        run: DGL_HOME=/home/runner/work/dgl-pyy-dev/dgl-pyy-dev bash ./script/build_dgl.sh -c -r
