name: build-dgl 

on: [push] 

jobs:
  build-dgl-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Pull DGL
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Pull Dependencies
        run: git submodule update --init --recursive

      - name: Create Conda Environment 
        run: bash ./script/create_dev_conda_env.sh -c -n dgl-dev-cpu -s  
      - name: init conda env
        run: conda init bash
      - name: Switch Conda Env
        run: conda activate dgl-dev-cpu
      - name: Build DGL
        run: bash ./script/build_dgl.sh -c -r
